const numberButtons =         document.querySelectorAll('[data-number]')
const operationButtons =      document.querySelectorAll('[data-operation]')
const equalsButton =          document.querySelectorAll('[data-equals]')
const deletesButton =         document.querySelectorAll('[data-delete]')
const allClearButton =        document.querySelectorAll('[data-allclear]')
const previousOperandButton = document.querySelectorAll('[data-previous-operand]')
const currentOperandButton =  document.querySelectorAll('[data-current-operand]')